platform :ios, '9.0'
use_frameworks!

target 'XLLKit_Example' do
  pod 'XLLKit', :path => '../'
  pod 'Then'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'SnapKit'
  pod 'JXPagingView/Paging'
  pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
  pod 'Charts'
  pod 'Toast-Swift'

  target 'XLLKit_Tests' do
    inherit! :search_paths

    
  end
end
