platform :ios, '9.0'
use_frameworks!

target 'XLLKit_Example' do
  pod 'XLLKit', :path => '../'
  pod 'Then'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'SnapKit'
  
  target 'XLLKit_Tests' do
    inherit! :search_paths

    
  end
end
